### ISSUE TITLE
can miniboss override entrypoint ?

### ISSUE THREAD

**Issue by cariaso** [afroisalreadyinu/miniboss#7]
I'm experimenting with miniboss, and trying to adapt from a docker-compose.yml that includes these lines

```
  nginx-gen:
    image: myimage/docker-gen:0.7.8
    container_name: nginx-gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
```

if I inspect the docker image with
`docker inspect -f '{{.Config.Entrypoint}}' d6f1786329e8`
the output is
`[/usr/local/bin/docker-gen]`

so it seems that the entrypoint from the docker-compose.yml is quite important. Is there a way with miniboss to achieve this sort of control?
